### ISSUE TITLE
Conflict between groovy versions

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#280]
When I apply the OSM workflow as described in issue #279 in DBeaver, I got the following error message:
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0-rc-2 and you are trying to load version 3.0.0

> groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0-rc-2 and you are trying to load version 3.0.0

The groovy version used as default version is 3.0.0-rc-2 (set using sdk-man). I have tried to set the default version to 3.0.0 but the problem remains (even if I close the groovy script and restart dbeaver).

An idea what to do ?

**Comment by ebocher** [comment]
Seems that OrbisData and Geoclimate have been updated to use Groovy 3.0.0 but nor Groovy RCP for Dbeaver : 
https://github.com/orbisgis/orbisrcp/pull/26

**Comment by gpetit** [comment]
So that could explain my issue #279 ?

**Comment by ebocher** [comment]
I think so.

**Comment by gpetit** [comment]
Ok. So do I have something to update ? with a command line ?
Or do I have to wait the validation of a PR ?

**Comment by ebocher** [comment]
Update your groovy plugin in Dbeaver. I have fixed the dep issues

**Comment by gpetit** [comment]
We are progressing ;-) But seems I have a conflict with `groovy-sql` because I have this error message
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:168)
	at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:329)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:282)
	at groovy.grape.Grape$1.run(Grape.java:174)
	at groovy.grape.Grape$1.run(Grape.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.grape.Grape.grab(Grape.java:160)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:377)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:336)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:231)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:218)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:528)
	at groovy.util.GroovyScriptEngine.createScript(GroovyScriptEngine.java:578)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:565)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:287)
	at org.codehaus.groovy.control.ErrorCollector.addException(ErrorCollector.java:135)
	at org.codehaus.groovy.control.SourceUnit.addException(SourceUnit.java:301)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:386)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:336)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:231)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:218)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:528)
	at groovy.util.GroovyScriptEngine.createScript(GroovyScriptEngine.java:578)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:565)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ebocher** [comment]
Go ./m2 remove orbisgis deps
Restart dbeaver
and re-install groovy plugin

**Comment by gpetit** [comment]
Hum ...
I removed the folder `.m2/repository/org/orbisgis/`
Then I restarted DBeaver ... but I was not able to update the Groovy console (can not click on Next ...). So I uninstalled the Groovy editor thanks to a DBeaver UI.
Then I reinstalled the Groovy editor and executed your code ... still the same error

Something strange, the `.m2/repository/org/orbisgis/` folder (in which there was a lot of sub-folders about postgis, osm, orbisdata, h2gis, ....) that I removed as not been recreated

**Comment by j3r3m1** [comment]
OK solved for me. The script works in DBeaver. @gpetit, try to update your geoclimate project in IntelliJ to recreate the .m2. I had the same problem and it worked.

**Comment by j3r3m1** [comment]
OK solved for me. The script works in DBeaver. @gpetit, try to update your geoclimate project in IntelliJ to recreate the .m2. I had the same problem and it worked.

**Comment by gpetit** [comment]
I will try but I want to merge my upcoming PR for the doc (which is in the pipe but it's on hold because of the current Github crash -> https://www.githubstatus.com/incidents/fxbbtd7mhz1c )

**Comment by gpetit** [comment]
Hum ... I'm a bit lost.

- I made a pull in order to be up-to-date with the geoclimate master branch
- I removed my `.m2` folder
- In IntelliJ I made a `mvn clean install` command --> my `.m2` folder is back
- In DBeaver I updated the Groovy editor
- I launched the workflow and still the same error

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerExtensionModuleFromProperties(MetaClassRegistryImpl.java:168)
	at groovy.grape.GrapeIvy.processCategoryMethods(GrapeIvy.groovy:329)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:282)
	at groovy.grape.Grape$1.run(Grape.java:174)
	at groovy.grape.Grape$1.run(Grape.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.grape.Grape.grab(Grape.java:160)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:377)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:336)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:231)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:218)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:528)
	at groovy.util.GroovyScriptEngine.createScript(GroovyScriptEngine.java:578)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:565)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:287)
	at org.codehaus.groovy.control.ErrorCollector.addException(ErrorCollector.java:135)
	at org.codehaus.groovy.control.SourceUnit.addException(SourceUnit.java:301)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:386)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.lambda$addPhaseOperationsForGlobalTransforms$4(ASTTransformationVisitor.java:336)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:880)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:650)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.doParseClass(GroovyScriptEngine.java:231)
	at groovy.util.GroovyScriptEngine$ScriptClassLoader.parseClass(GroovyScriptEngine.java:218)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
	at groovy.util.GroovyScriptEngine.loadScriptByName(GroovyScriptEngine.java:528)
	at groovy.util.GroovyScriptEngine.createScript(GroovyScriptEngine.java:578)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:565)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by j3r3m1** [comment]
Do not know what is the right solution to your problem. However, the potential difference with you could be the groovy version used (I have set default version as 3.0.0 instead of 3.0.0-rc-2
Here is a brief description how to change the parameters:
1. Download sdk
2. display the list of groovy installed versions:
sdk list groovy
3. if the default one is not the one you want, you need to do:
sdk default groovy 3.0.0 (for example)
4. if this version is not install you will have to install it:
sdk install groovy 3.0.0


If you want to install a version not directly dowloadable (for example 3.0.0-rc-2):
http://apache.crihan.fr/dist/groovy/3.0.0-rc-2/sources/apache-groovy-src-3.0.0-rc-2.zip

Then in a terminal, you point the folder where you have unzip your groovy version and you give him an alias (e.g. 3.0.0-rc-2SNAP): 
sdk install groovy 3.0.0-rc-2SNAP /home/decide/Software/groovy-3.0.0-rc-2

**Comment by gpetit** [comment]
I guess you were talking about SDKMan ?
I installed this app and followed these instructions : https://sdkman.io/install
And I get 
```
xxx@xxx:~/geoclimate$ sdk version
==== BROADCAST ===================================================
* 2020-02-17: Groovy 3.0.1 released on SDKMAN! #groovylang
* 2020-02-17: Gradle 6.2 released on SDKMAN! #gradle
* 2020-02-17: Concurnas 1.14.019 released on SDKMAN! #concurnas
==================================================================
SDKMAN 5.7.4+362
```
So that would mean that I'm on Groovy 3.0.1 ?

**Comment by gpetit** [comment]
> Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2

This message means that my machine is using Groovy 3.0.0 while Geoclimate ask to use Groovy 3.0.0-rc-2 ? Right ?

**Comment by gpetit** [comment]
I also tried in the Groovy console

```groovy
groovy> @GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/') 
groovy> @Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT') 
groovy> import org.orbisgis.orbisprocess.geoclimate.Geoclimate 
groovy> Geoclimate.logger = logger 
groovy> def process = Geoclimate.Workflow.OSM() 
groovy> process.execute(configurationFile:'/tmp/config.json') 
groovy>                     
groovy> logger.info process.results.outputMessage 
 
1 compilation error:

Exception thrown

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.0 and you are trying to load version 3.0.0-rc-2
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by gpetit** [comment]
... and yes I was up-to-date with Geoclimate (I made a `git pull orbisgis master` before doing the `mvn clean install`)

**Comment by SPalominos** [comment]
Issue caused by the `.groovy` cache which was keeping old dependencies version using `groovy-3.0.0-rc2`.
